directives: (directive ";")*
?directive: let | reduce
let: "let" VARWORD "=" expr
reduce: "reduce" expr
list: "[" subexpr* "]"
?expr: subexpr | apply
apply: expr subexpr
?subexpr: var | mlambda | "(" expr ")" | list
mlambda: ("λ" | "\\") varlist "." expr
varlist: VARWORD*
var: VARWORD
VARWORD: ("_"|LETTER|DIGIT)+

COMMENT: /#[^\n]*/
%ignore WS
%ignore COMMENT

%import common.LETTER
%import common.DIGIT
%import common.WS
