directives: (directive ";")*
?directive: let | magic | reduce
let: "let" VARWORD "=" expr
magic: "magic" VARWORD VARWORD
reduce: "reduce" expr

?expr: subexpr | apply
?subexpr: var | mlambda | "(" expr ")" | list
apply: expr subexpr
var: VARWORD
mlambda: ("λ" | "\\") varlist "." expr
list: "[" subexpr* "]"

varlist: VARWORD*
VARWORD: ("_"|LETTER|DIGIT)+

COMMENT: /#[^\n]*/
%ignore WS
%ignore COMMENT

%import common.LETTER
%import common.DIGIT
%import common.WS
