#!/usr/bin/env python3
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import pathlib

from pylambdac import markcode
from pylambdac import parse
import pylambdac.processor

def file_text(tf):
    if tf.suffix == ".md":
        with tf.open() as fp:
            return markcode.blockcodes_as_string(fp)
    else:
        return tf.read_text()

def parse_args():
    p = argparse.ArgumentParser(allow_abbrev=False)
    p.add_argument("--outdir", type=pathlib.Path)
    p.add_argument("olcfile", nargs='*', type=pathlib.Path)
    return p.parse_args()

def main():
    args = parse_args()
    drawings = []
    for tf in args.olcfile:
        print(f"==== {tf}")
        directives = parse.parse_directives(file_text(tf))
        processor = pylambdac.processor.Processor(args)
        processor.process(directives)
        drawings.extend(processor.drawings)
    if args.outdir:
        body = "\n".join(f"<p><img src=\"{d}\"/></p>" for d in drawings)
        (args.outdir / "index.html").write_text(
            f"<html><body>{body}</body></html>")

if __name__ == '__main__':
    main()
