#!/usr/bin/env python3

import argparse
import pathlib

import all_tests

def parse_args():
    p = argparse.ArgumentParser(allow_abbrev=False)
    p.add_argument("--test", required=True)
    p.add_argument("--source",type=pathlib.Path, required=True)
    return p.parse_args()

def main():
    args = parse_args()
    all_tests.all_tests()[args.test].fixup_file(args.source)

if __name__ == '__main__':
    main()
