#!/usr/bin/env python3

import paths
import parse

def checkexpr(expr):
    print("==============")
    print(expr)
    newexpr = parse.parse_expr(str(expr))
    print(" ".join(expr.prefixcode()))
    print(" ".join(newexpr.prefixcode()))
    assert expr == newexpr
    print(" ".join(expr._prefixcode([])))
    print("==============")

def main():
    testfiles = paths.top / "testfiles"
    for tf in testfiles.iterdir():
        print(f"==== {tf}")
        directives = parse.parse_directives(tf.read_text())
        for d in directives.children:
            print(d.pretty())
            if d.data == "let":
                checkexpr(d.children[1])
            elif d.data == "test":
                checkexpr(d.children[0])
                checkexpr(d.children[1])
                print("Equiv?", d.children[0].equiv(d.children[1]))

if __name__ == '__main__':
    main()
