#!/usr/bin/env python3
# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import pathlib
import sys

sys.path.append(str(pathlib.Path(__file__).parent.parent))

from tests import all_tests

def parse_args():
    p = argparse.ArgumentParser(allow_abbrev=False)
    p.add_argument("--test", required=True)
    p.add_argument("--source",type=pathlib.Path, required=True)
    return p.parse_args()

def main():
    args = parse_args()
    all_tests.all_tests()[args.test].fixup_file(args.source)

if __name__ == '__main__':
    main()
